//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelMvcProje.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbOtelEntities1 : DbContext
    {
        public DbOtelEntities1()
            : base("name=DbOtelEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblHakkimda> TblHakkimdas { get; set; }
        public virtual DbSet<TblIletisim> TblIletisims { get; set; }
        public virtual DbSet<TblMesaj> TblMesajs { get; set; }
        public virtual DbSet<TblYeniKayit> TblYeniKayits { get; set; }
        public virtual DbSet<TblMisafir> TblMisafirs { get; set; }
        public virtual DbSet<TblRezervasyon> TblRezervasyons { get; set; }
        public virtual DbSet<TblMesaj2> TblMesaj2 { get; set; }
        public virtual DbSet<TblOda> TblOdas { get; set; }
        public virtual DbSet<TblMailBirakanlar> TblMailBirakanlars { get; set; }
        public virtual DbSet<TblEkibimiz> TblEkibimizs { get; set; }
        public virtual DbSet<TblOnRezervasyon> TblOnRezervasyons { get; set; }
    }
}
